# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:8

stages:
  - lint
  - build
  - test

lint:
  stage: lint
  script:
    - yarn
    - npm run lint

test:
  stage: test
  variables:
    APT_CACHE_DIR: apt-cache
  script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt install firefox-esr -y --no-install-recommends
    - firefox --version
    - yarn
    - npm run unit

build:
  stage: build
  script:
    - yarn
    - npm run build
  artifacts:
    paths:
    - dist/
